# Generated by Django 4.2.16 on 2024-11-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
